CREATE DATABASE IF NOT EXISTS academy;
USE academy;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(120) NOT NULL UNIQUE,
	password VARCHAR(120) NOT NULL,
	role VARCHAR(50) DEFAULT 'super_admin',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	status VARCHAR(20) DEFAULT 'active',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	type ENUM('income', 'expense') NOT NULL,
	amount DECIMAL(10, 2) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
	id INT AUTO_INCREMENT PRIMARY KEY,
	student_id INT NOT NULL,
	date DATE NOT NULL,
	status ENUM('present', 'absent') NOT NULL,
	FOREIGN KEY (student_id) REFERENCES students(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS classes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(120) NOT NULL,
	days VARCHAR(120) NOT NULL,
	plans VARCHAR(255) NOT NULL,
	enrolled INT NOT NULL DEFAULT 0,
	level VARCHAR(50) NOT NULL,
	coach VARCHAR(120) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class_schedules (
	id INT AUTO_INCREMENT PRIMARY KEY,
	class_name VARCHAR(120) NOT NULL,
	level VARCHAR(50) NOT NULL,
	day VARCHAR(20) NOT NULL,
	time TIME NOT NULL,
	duration INT NOT NULL,
	instructor VARCHAR(120) NOT NULL,
	location VARCHAR(120) DEFAULT '',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, email, password, role)
SELECT 'Administrator', 'admin@academy.com', '123456', 'super_admin'
WHERE NOT EXISTS (
	SELECT 1 FROM users WHERE email = 'admin@academy.com'
);
