# Generated by Django 4.2.7 on 2026-03-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientattendance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clients.client'),
        ),
        migrations.AlterUniqueTogether(
            name='clientattendance',
            unique_together={('client', 'date', 'academy_class')},
        ),
    ]
