# Generated by Django 6.0.3 on 2026-03-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('classes', '0005_remove_classschedule_specific_date'),
        ('clients', '0003_client_one_time_plans'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientattendance',
            unique_together={('client', 'date')},
        ),
        migrations.AlterField(
            model_name='clientattendance',
            name='academy_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='classes.academyclass'),
        ),
    ]
