# Generated by Django 6.0.3 on 2026-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='auto_renew_clients',
            field=models.BooleanField(default=False, help_text='Default auto-renew value for clients assigned to this plan'),
        ),
    ]
