# Generated by Django 4.2.7 on 2026-03-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('facilities', 'Facilities'), ('salaries', 'Salaries'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('medical', 'Medical'), ('training', 'Training Materials'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text='Rate used to convert to base currency', max_digits=12)),
                ('amount_base', models.DecimalField(decimal_places=2, default=0, help_text='Amount in base currency (auto-calculated)', max_digits=12)),
                ('base_currency', models.CharField(default='USD', max_length=10)),
                ('expense_date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('paid_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
