# Generated by Django 4.2.7 on 2026-03-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('duration_days', models.IntegerField(default=30, help_text='Number of days this plan is valid for')),
                ('features', models.TextField(blank=True, help_text='Comma-separated list of features, e.g. "3 sessions/week, Kit included"')),
                ('max_sessions_per_week', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
