# Generated by Django 6.0.3 on 2026-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
